name: Cypress Tests

on: [push]

jobs:
  pre-job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths_ignore: '["**.md", "docs/**", "firestore-tests/**", "src/**/*.spec.ts"]'
          cancel_others: true

  cypress:
    needs: pre-job
    if: ${{ needs.pre-job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache firebase emulators
      uses: actions/cache@v2
      with:
        path: ~/.cache/firebase/emulators
        key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: 'https://npm.pkg.github.com'
        scope: '@mn-pollinators'
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        record: true
        start: npm run firebase:emulator
        command: npm run e2e -- --record
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
